sudo: required
language: generic
services:
  - docker

before_install: 
  - docker build -t gansiz/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true gansiz/docker-react npm run test


deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-east-1-992382362584"
  bucket_path: "frontend"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"